---
- name: Add PostgreSQL Database
  postgresql_db:
    name: "{{postgres_kong_database}}"
    login_user: postgres
    login_password: postgres
    state: present


- name: Add PostgreSQL User
  postgresql_user:
    name: "{{postgres_kong_user}}"
    password: "{{postgres_kong_pass_hash}}"
    encrypted: yes
    login_user: postgres
    login_password: postgres
    priv: ALL
    db: "{{postgres_kong_database}}"
    state: present
